export interface adquiriente {
  CORREO: String;
  DEPARTAMENTOADQUIRIENTE: String;
  DESTINO: any[];
  DIRECCIONADQUIRIENTE:String;
  DISTRITOADQUIRIENTE:String;
  NUMERODOCUMENTOADQUIRIENTE:String;
  PROVINCIAADQUIRIENTE:String;
  RAZONSOCIALADQUIRIENTE:String;
  TIPODOCUMENTOADQUIRIENTE:String;
  UBIGEOADQUIRIENTE:String;
}
